### PR TITLE
Fix a bunch of issues

### PR DESCRIPTION
**Pull request by ficristo**
- update htmllint to 0.7.0 and move node deps inside top level package.json
- add ESLint configuration
- actually pass the options to htmllint
- move error formatting on node domain
  - show the description of the error
  - sort errors by line
  - fix column position (col -> ch)
  - remove some console statements

/cc  @mlochbaum

### CODE REVIEW

**Comment by mlochbaum** [comment]
This should all be downloadable from the registry in version 0.2.0, but I haven't installed Brackets to check.

**Comment by ficristo** [comment]
Thank you!
Could you also update the version in the package.json? The version mismatch confuses the extension manager.

**Comment by mlochbaum** [comment]
It looks like is says 0.2.0. What exactly do I need to change?

**Comment by ficristo** [comment]
Nevermind, probably I had my dev version still linked.
Reinstalled from scratch worked.
Thanks again!

**Pull request merged**
